title: Portfolio of Elizabeth Miller

markdown: kramdown

email: elizabethm@innerstate.org

description: 

baseurl: "" # the subpath of your site, e.g. /blog/

url: http://innerstate.org 

github_username:  agentbetty

# Build settings
markdown: kramdown

exclude:
- Rakefile
- README.md